baseURL = "http://example.org/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
title = "Davide & Jennifer"

[languages]
  [languages.en]
    weight = 0
    languageName = "English"
    contentDir = "content/en"
  [languages.it]
    weight = 1
    languageName = "Italiano"
    contentDir = "content/it"
  [languages.es]
    weight = 2
    languageName = "Espa√±ol"
    contentDir = "content/es"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true