baseURL = "http://example.org/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
title = "Davide & Jennifer"

[languages]
  [languages.en]
    weight = 0
    languageName = "English"
    contentDir = "content/en"
    flag = "ğŸ‡¦ğŸ‡º"
  [languages.it]
    weight = 1
    languageName = "Italiano"
    contentDir = "content/it"
    flag = "ğŸ‡®ğŸ‡¹"
  [languages.es]
    weight = 2
    languageName = "EspaÃ±ol"
    contentDir = "content/es"
    flag = "ğŸ‡¨ğŸ‡´"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true