[[main]]
    identifier = "menu.ceremony"
    pageRef = "/ceremony"
    weight = 1
[[main]]
    identifier = "menu.travel"
    pageRef = "/travel"
    weight = 2
[[main]]
    identifier = "menu.story"
    pageRef = "/story"
    weight = 3
[[main]]
    identifier = "menu.registry"
    pageRef = "/registry"
    weight = 4
[[main]]
    identifier = "FAQ"
    pageRef = "/faq"
    weight = 5
