# Hugo config file
baseURL = "https://atteggiani.github.io/wedding-website/"
languageCode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
title = "Davide & Jennifer"

# Disable multilingual handling for the homepage
disableLanguages = []

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
  [languages.es]
    weight = 2
    languageName = "Espa√±ol"
  [languages.it]
    weight = 3
    languageName = "Italiano"

[outputs]
  home = ["HTML"]

[params]
  supabaseUrl = "https://bcyxjsqpvkywiuvaskvs.supabase.co"
  supabaseAnonKey = "$SUPABASE_ANON_KEY"
