baseURL = "http://example.org/"
defaultContentLanguage = "en"
theme= "wedding-theme"
title = "Davide & Jennifer"

[Languages]
    [Languages.en]
        title = "Multilingual Hugo Example"
        weight = 0
        languagename = "English"
        
        [[Languages.en.menu.main]]
            url = "/"
            name = "Home"
            weight = 1
        [[Languages.en.menu.main]]
            url = "/about/"
            name = "About"
            weight = 0
    
    [Languages.it]
        weight = 1
        languagename = "Italiano"
        
        [[Languages.it.menu.main]]
            url = "/"
            name = "Home"
            weight = 1
        [[Languages.it.menu.main]]
            url = "/about/"
            name = "About"
            weight = 0
    
    [Languages.es]
        weight = 2
        languagename = "Espa√±ol"
        
        [[Languages.es.menu.main]]
            url = "/"
            name = "Home"
            weight = 1
        [[Languages.es.menu.main]]
            url = "/about/"
            name = "About"
            weight = 0