baseURL = "http://example.org/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
title = "Davide & Jennifer"

[languages]
  [languages.en]
    weight = 0
    languageName = "English"
    contentDir = "content/en"
  [languages.it]
    weight = 1
    languageName = "Italiano"
    contentDir = "content/it"
  [languages.es]
    weight = 2
    languageName = "Espa√±ol"
    contentDir = "content/es"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menus]
  [[menus.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menus.main]]
    identifier = "story"
    name = "Our Story"
    url = "/story/"
    weight = 20
  
[params]
  date = "02.09.2026"
  bannerTitle = "D & J 02.09.2026"

